apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-api-hpa
  namespace: mbrzoskowski
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 10
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
  - type: Pods
    pods:
      metricName: packects-per-second
      targetAverageValue: 1k