apiVersion: v1
kind: Service
metadata:
  name: api-nodeport

spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31100
    
  selector:
    app: ticket-app
    type: API