apiVersion: v1
kind: Service 
metadata:
  name: api-clusterip
  labels:
    app: ticket-app
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: ticket-app
    type: API