apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
    
  selector:
    app: ticket-app
    type: frontend