apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-deployment
  labels:
    app: my-app
    type: cache

spec:
  template:
    metadata:
      name: my-redis-pod
      labels:
        app: my-app
        type: cache
    spec:
      containers:
        - name: my-redis-container
          image: redis:alpine
  
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      type: cache


