apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: ticket-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: ticket-app
  type: ClusterIP