apiVersion: v1
kind: Service 
metadata:
  name: my-backend-nodeport

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31100
  
  selector:
      app: my-app
      type: backend
