apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  labels:
    app: my-app
    type: backend

spec:
  template:
    metadata:
      name: my-backend-pod
      labels:
        app: my-app
        type: backend
    spec:
      containers:
        - name: my-backend-container
          image: pikussmietnikus/mybackend
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      type: backend
