apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: ticket-app
    type: backend

spec:
  template:
    metadata:
      name: backend-pod
      labels:
        app: ticket-app
        type: backend
    spec:
      containers:
        - name: backend-container
          image: pikussmietnikus/ticket-backend
  replicas: 1
  selector:
    matchLabels:
      app: ticket-app
      type: backend