/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.cloud;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

class GcpTtsTest {

    @Test
    void shouldSynthesizeVoice() throws IOException {

        // given
        GcpTts underTest = new GcpTts();

        // when
        underTest.textToSpeech();

        // then
        Files.exists(Paths.get("build/output.mp3"));
    }

    @Test
    void shouldSynthesizeVoiceSSML() throws IOException {

        // given
        GcpTts underTest = new GcpTts();

        // when
        underTest.textToSpeech();

        // then
        Files.exists(Paths.get("build/outputSSML.mp3"));
    }
}
