version: '3'

services:
  mybackend:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./mybackend
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=myappuser
      - POSTGRES_HOST=mypostgres
      - REDIS_HOST=myredis
    
  mynginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./mynginx
    ports:
      - '9090:80'
    
  myfrontend:
    build: 
      dockerfile: Dockerfile
      context: ./myfrontend
    volumes:
      - /opt/app/node_modules
      - ./myfrontend:/opt/app
    
  mypostgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx

  myredis:
    image: 'redis:alpine'

  
