apiVersion: v1
kind: Service 
metadata:
  name: backend-clusterip
  labels:
    app: ticket-app
spec:
  type: ClusterIP
  ports:
    - port: 6000
      targetPort: 6000
  selector:
    app: ticket-app
    type: backend