apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport

spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 31200
    
  selector:
    app: ticket-app
    type: backend