version: "3.7"
services:
  api:
    image: pikussmietnikus/rest_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
  db:
    image: pikussmietnikus/my_postgres
    volumes:
      - /postgresdata:/var/lib/postgresql/data
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_DATABASE: ${POSTGRESQL_DB}
    ports:
      - "5432:5432"
  pgadmin:
    image: pikussmietnikus/my_pgadmin
    ports: 
      - "80:80"
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
        - db
    command:
      - start-dev