pipeline {
 agent any

        options {
            timeout(5)
            gitLabConnection('GitLab')
        }
        triggers {
            gitlab(
                triggerOnPush: true,
                triggerOnMergeRequest: true,
                branchFilterType: 'All',
                addVoteOnMergeRequest: true)
        }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Verify tooling') {
            steps {
                sh '''
                docker version
                docker info
                docker compose version
                curl --version
            '''
            }
        }
        stage('Docker Build Compose') {
            steps {
               sh 'docker compose up -d --no-color --wait'
               sh 'docker compose ps'
            }
        }
        stage('Pushing Docker Image to Dockerhub') {
                    steps {
                        script {
                            docker.withRegistry('https://registry.hub.docker.com', 'docker_credential') {
                                docker.image("pikussmietnikus/rest_api").push()
                                docker.image("pikussmietnikus/my_postgres").push()
                                docker.image("pikussmietnikus/my_pgadmin").push()
                            }
                        }
                    }
                }
    }
}